force-app/main/default/objects/Contact/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>28</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IBANAccountOwner__c.field-meta.xml
<CustomField>
    <fullName>IBANAccountOwner__c</fullName>
    <label>IBANAccountOwner</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer__c/Volunteer__c.object-meta.xml
<CustomObject>
    <label>Volunteer</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Volunteer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer__c/fields/CompensationAndExpensesPayed__c.field-meta.xml
<CustomField>
    <fullName>CompensationAndExpensesPayed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CompensationAndExpensesPayed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteers</relationshipLabel>
    <relationshipName>Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Volunteer__c/fields/IndividualCompensationTotal__c.field-meta.xml
<CustomField>
    <fullName>IndividualCompensationTotal__c</fullName>
    <formula>VolunteerShift__r.DefaultCompensation__c  +  IndividualCompensation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IndividualCompensationTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Volunteer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VolunteerStatusesPicklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Volunteer__c/fields/VolunteerShift__c.field-meta.xml
<CustomField>
    <fullName>VolunteerShift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VolunteerShift</label>
    <referenceTo>VolunteerShift__c</referenceTo>
    <relationshipLabel>Volunteers</relationshipLabel>
    <relationshipName>Volunteers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VolunteerShift__c/VolunteerShift__c.object-meta.xml
<CustomObject>
    <label>VolunteerShift</label>
    <nameField>
        <label>VolunteerShift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VolunteerShifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VolunteerShift__c/fields/CompensationTotalShiftLeader__c.field-meta.xml
<CustomField>
    <fullName>CompensationTotalShiftLeader__c</fullName>
    <formula>DefaultCompensation__c  +  IndividualCompensationShiftLeader__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CompensationTotalShiftLeader</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VolunteerShift__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>VolunteerShifts</relationshipLabel>
    <relationshipName>VolunteerShifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VolunteerShift__c/fields/IsIBANPayment__c.field-meta.xml
<CustomField>
    <fullName>IsIBANPayment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsIBANPayment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VolunteerShift__c/fields/ShiftLeader__c.field-meta.xml
<CustomField>
    <fullName>ShiftLeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ShiftLeader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>VolunteerShifts</relationshipLabel>
    <relationshipName>VolunteerShifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/XMLGenerator.cls
public with sharing class XMLGenerator {
    public class FlowInput {
        @InvocableVariable public Id eventId;
        @InvocableVariable public Boolean isCompensationAndExpensesStatusChanged;
        @InvocableVariable public Boolean isExportForAlreadyPaid;
    }
    public class FlowOutput {
        @InvocableVariable public String message;
        @InvocableVariable public Boolean isBatchNeeded = false;
        @InvocableVariable public Id jobId;
    }

    @InvocableMethod
    public static List<FlowOutput> generateXML(List<FlowInput> inputs) {
        List<FlowOutput> results = new List<FlowOutput>();
        FlowOutput output = new FlowOutput();
        Id eventId = inputs[0].eventId;
        Boolean isCompensationAndExpensesStatusChanged = inputs[0].isCompensationAndExpensesStatusChanged;
        Boolean isExportForAlreadyPaid = inputs[0].isExportForAlreadyPaid;
        for(VolunteerShift__c shift: [SELECT Id,
                                             ShiftLeader__r.IBAN__c,
                                             CompensationAndExpensesPayed__c
                                      FROM VolunteerShift__c
                                      WHERE Event__c =: eventId
                                      AND IsIBANPayment__c = true
                                      AND CompensationTotalShiftLeader__c != null
                                      AND CompensationTotalShiftLeader__c > 0
                                      AND ShiftLeader__r.IBANAccountOwner__c != null
                                      LIMIT 50000
        ]){
            Boolean isLeaderValid = true;
            if(String.isBlank(shift.ShiftLeader__r.IBAN__c)){
                isLeaderValid = false;
            }
            if(isExportForAlreadyPaid == false && shift.CompensationAndExpensesPayed__c == true){
                isLeaderValid = false;
            }
            if(isLeaderValid == true) {
                output.isBatchNeeded = true;
                break;
            }
        }
        if(output.isBatchNeeded == true) {
            output.jobId = Database.executeBatch(new BulkXmlGenerator(inputs), 200);
        }
        if(output.isBatchNeeded == false) {
            for(Volunteer__c volunteer:[SELECT Id,
                                             Contact__r.IBAN__c,
                                             CompensationAndExpensesPayed__c
                                      FROM Volunteer__c
                                      WHERE VolunteerShift__r.Event__c =: eventId
                                      AND VolunteerShift__r.IsIBANPayment__c = true
                                      AND IndividualCompensationTotal__c != null
                                      AND Contact__r.IBANAccountOwner__c != null
                                      AND Status__c = :DataHelper.VOLUNTEER_STATUS_PARTICIPATION
                                      LIMIT 50000
        ]){
            Boolean isVolunteerValid = true;
            if(String.isBlank(volunteer.Contact__r.IBAN__c)){
                isVolunteerValid = false;
            }
            if(isExportForAlreadyPaid == false && volunteer.CompensationAndExpensesPayed__c == true){
                isVolunteerValid = false;
            }
            if(isVolunteerValid == true) {
                output.isBatchNeeded = true;
                break;
            }
        }
    }
    if(output.isBatchNeeded == true) {
        output.jobId = Database.executeBatch(new BulkXmlGenerator(inputs), 200);
    }
    else{
        output.message = System.Label.EventErrorLabel;
    }
    results.add(output);
    return results;
    }
}